# Generated by Django 5.1.1 on 2024-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
