# Generated by Django 5.1.1 on 2024-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_article_image_alter_featuredcourse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tip/'),
        ),
    ]
